apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.usvc.name }}
    labels:
       app: {{ .Values.usvc.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.usvc.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.usvc.name }}
    spec:
        containers:
          - name: {{ .Values.usvc.name }}
            image: {{ .Values.usvc.image.name }}:{{ .Values.usvc.image.tag }}
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: {{ .Values.usvc.port }}
            workDir: /
            command: [ "/bin/sleep", "36525d" ]
            volumeMounts:
            - name: config-volume
              mountPath: /etc/worker-config.json
        volumes:
          - name: config-volume
            configMap:
              name: python-opencv-config
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.usvc.service }}
spec:
  selector:
    app: {{ .Values.usvc.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.usvc.port }}