apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.usvc.name }}
    labels:
       app: {{ .Values.usvc.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.usvc.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.usvc.name }}
    spec:
         containers:
         - name: {{ .Values.usvc.name }}
           image: {{ .Values.usvc.image.name }}:{{ .Values.usvc.image.tag }}
           ports:
           - containerPort: {{ .Values.usvc.port }}
           env:
           - name: "MYSQL_ROOT_PASSWORD"
             value:  {{quote .Values.usvc.password}}
           - name: "MYSQL_DATABASE"
             value:  {{quote .Values.usvc.name}}
           - name: "MYSQL_USER"
             value:  {{quote .Values.usvc.user}}
           - name: "MYSQL_PASSWORD"
             value:  {{quote .Values.usvc.password}}