  {{- if .Values.persistency.enabled }}
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: {{ .Values.usvc.claim }}
   labels:
     app:  {{ .Values.usvc.name }}
 spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
{{- end }}